.TH cover-thumbnailer 1 "Sun, 12 Jul 2020" "version 0.10.0" "COVER THUMBNAILER"

.SH NAME
cover-thumbnailer \- display music covers and more in nautilus

.SH SYNOPSIS
.B cover-thumbnailer
.I <PATH_OF_FOLDER> <OUTPUT_PNG_FILE>

.SH DESCRIPTION
Cover thumbnailer generates folder thumbnails for various file browser on
Linux. It displays music album covers, preview of pictures which are in a
folder and more.

.SH CONFIGURATION
Use cover-thumbnailer-gui

.SH WEB SITE
https://github.com/flozz/cover-thumbnailer

.SH AUTHOR
Fabien Loison <flo at flogisoft dot com>

.SH REPORTING BUGS
Report bugs to <https://github.com/flozz/cover-thumbnailer/issues>.

.SH COPYRIGHT
Copyright  ©  2009–2020 Fabien Loison <flo at flogisoft dot com>.
Cover thumbnailer is free software under GNU GPL v3+ licence <http://gnu.org/licenses/gpl.html>,
you are free to modify and redistribute it under the terms of the license.


