.TH cover-thumbnailer-gui 1 "Mon, 31 Jul 2023" "version 0.10.1" "COVER THUMBNAILER GUI"

.SH NAME
cover-thumbnailer-gui \- configuration tool for cover-thumbnailer

.SH SYNOPSIS
.B cover-thumbnailer-gui

.SH DESCRIPTION
Cover thumbnailer GUI is an graphical configuration tool for Cover Thumbnailer

.SH WEB SITE
https://github.com/flozz/cover-thumbnailer

.SH AUTHOR
Fabien Loison <flo at flogisoft dot com>

.SH REPORTING BUGS
Report bugs to <https://github.com/flozz/cover-thumbnailer/issues>.

.SH COPYRIGHT
Copyright  ©  2009–2023 Fabien Loison <flo at flogisoft dot com>.
Cover thumbnailer is free software under GNU GPL v3+ licence <http://gnu.org/licenses/gpl.html>,
you are free to modify and redistribute it under the terms of the license.
