.TH cover-thumbnailer 1 "Sun, 25 Apr 2010" "version 0.8" "COVER THUMBNAILER"
 
.SH NAME
cover-thumbnailer \- display music covers and more in nautilus

.SH SYNOPSIS
.B cover-thumbnailer
.I <PATH_OF_FOLDER> <OUTPUT_PNG_FILE>

.SH DESCRIPTION
Cover thumbnailer is a small Python script which displays music 
album covers in nautilus, preview of pictures which are in a 
folder and more.
The script fits in nautilus like any other thumbnailer of the
GNOME thumbnail factory; so you don't have to run it manually
to generate thumbnails.

.SH CONFIGURATION
Use cover-thumbnailer-gui

.SH WEB SITE
http://software.flogisoft.com/cover-thumbnailer/

.SH AUTHOR
Fabien Loison <flo@flogisoft.com>

.SH REPORTING BUGS
Report bugs to <flo@flogisoft.com>.

.SH COPYRIGHT
Copyright  ©  2009–2010 Fabien Loison <flo@flogisoft.com>.
Cover thumbnailer is free software under GNU GPL v3+ licence <http://gnu.org/licenses/gpl.html>,
you are free to modify and redistribute it under the terms of the license.


